// Code generated by "prefix "; DO NOT EDIT.

package uom

// Prefix the scalar value by which the unit atom is multiplied if combined with the prefix
type Prefix float64

const (
	yotta Prefix = 1e24
	zetta Prefix = 1e21
	exa   Prefix = 1e18
	peta  Prefix = 1e15
	tera  Prefix = 1e12
	giga  Prefix = 1e9
	mega  Prefix = 1e6
	kilo  Prefix = 1e3
	hecto Prefix = 1e2
	deka  Prefix = 1e1
	deci  Prefix = 1e-1
	centi Prefix = 1e-2
	milli Prefix = 1e-3
	micro Prefix = 1e-6
	nano  Prefix = 1e-9
	pico  Prefix = 1e-12
	femto Prefix = 1e-15
	atto  Prefix = 1e-18
	zepto Prefix = 1e-21
	yocto Prefix = 1e-24
	kibi  Prefix = 1024
	mebi  Prefix = 1048576
	gibi  Prefix = 1073741824
	tebi  Prefix = 1099511627776
)
